version: '3.8'

services:
  postgres_dev:
    image: "postgres:16.0-alpine3.18"
    env_file:
      - db/.env.development
    ports:
      - "5432:5432"
  api_auth_dev:
    build:
      context: ..
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - ./app/.env.development
    ports:
      - "8080:8080"
    depends_on:
      - postgres_dev
  nginx_proxy:
    build:
      context: ..
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api_auth_dev
